baseURL = 'https://www.csz.net/'
languageCode = 'zh-cn'
title = 'CSZNET'
theme = "csz"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Proj'
pageRef = '/proj'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'base16-snazzy'
    tabWidth = 4